name: 构件ariaNg镜像
on:
  #防止fork乱用action设置只能手动触发构建
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送到Dockerhub镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/arm64/v8,linux/ppc64le
          push: true
          tags: |
            huangdekai/ariang:${{ secrets.VERSION }}
